[[redirects]]
  from = "/i/*"
  to = "https://na.cx/i/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/*"
  to = "https://fodi.327.workers.dev/:splat"
  status = 200
  force = true
