[build]
  functions = "functions"
  
[[redirects]]
  from = "/i/*"
  to = "https://na.cx/i/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/*"
  to = "https://fodi.327.workers.dev/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ig/*"
  to = "https://www.instagram.com/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
  
[[redirects]]
  from = "/static/*"
  to = "https://www.instagram.com/static/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
  
[[redirects]]
  from = "/assets/*"
  to = "https://lihkg.com/assets/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
