[build]
  functions = "functions"
  
[[redirects]]
  from = "/i/*"
  to = "https://na.cx/i/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/*"
  to = "https://fodi.327.workers.dev/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "/jybsh/*"
  to = "http://qq.server.trading/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ig/*"
  to = "https://scontent.cdninstagram.com/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "/utv"
  to = "http://m-epg.cmishow.com/?s=104&p=mLiveHome&k=1&v=1&c=1&a=852&i=3&catId=1436&l=zh_TW"
  status = 200
  force = true
# query = {s = "104", p = "mLiveHome", k = "1", v = "1", c = "1", a = "852", i = "3", catId = "1436", l = "zh_TW"}
  
[[redirects]]
  from = "/assets/*"
  to = "https://lihkg.com/assets/:splat"
  status = 200
  force = true
