[build]
  functions = "functions"

[[redirects]]
  from = "/ig/*"
  to = "https://scontent.cdninstagram.com/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "/thread/*"
  to = "https://lihkg.com/api_v2/thread/:splat"
  status = 200
  force = true
  headers = {user-agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36", Referer = "https://lihkg.com"}
  
[[redirects]]
  from = "/assets/*"
  to = "https://cdn.lihkg.com/assets/:splat"
  status = 200
  force = true
